---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
     - name: Display IPLINFO
       zos_operator:
         cmd: "D IPLINFO"

